In [2]:
import numpy as np

In [2]:
a2=np.array([[1,2.0,3.3],
            [4,5,6.5]])

In [4]:
a3=np.array([[[1,3,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [5]:
a3.shape


(3, 2, 3)

In [6]:
a2.shape


(2, 3)

In [7]:
a2.size


6

In [8]:
a3.size

18

In [9]:
a3.ndim


3

In [10]:
a3.shape

(3, 2, 3)

In [11]:
ones=np.ones((2,3))

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros=np.zeros((2.3))

TypeError: expected a sequence of integers or a single integer, got '2.3'

In [14]:
zeros=np.zeros((2,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array=np.random.randint(0,10,size=(3,5))

In [19]:
random_array

array([[5, 3, 7, 1, 8],
       [0, 9, 3, 3, 2],
       [0, 8, 8, 0, 0]])

In [20]:
np.unique(random_array)

array([0, 1, 2, 3, 5, 7, 8, 9])

In [21]:
random_array**2

array([[25,  9, 49,  1, 64],
       [ 0, 81,  9,  9,  4],
       [ 0, 64, 64,  0,  0]])

In [22]:
random_array%7

array([[5, 3, 0, 1, 1],
       [0, 2, 3, 3, 2],
       [0, 1, 1, 0, 0]], dtype=int32)

In [23]:
np.sum(random_array)

57

In [24]:
np.max(random_array)

9

In [25]:
np.mean(random_array)

3.8

In [28]:
np.std(random_array)
#np.var(random_array)


3.2903900478008175

In [16]:
no_items_each_day=np.array([[2,7,1],[9,4,16],[11,14,18],[13,13,16],[15,18,9]])

In [17]:
no_items_each_day

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [20]:
prices=np.array([[10],[8],[12]])
prices

array([[10],
       [ 8],
       [12]])

In [21]:
total=np.dot(no_items_each_day,prices)

In [22]:
total

array([[ 88],
       [314],
       [438],
       [426],
       [402]])

In [8]:
import pandas as pd

In [23]:
df=pd.DataFrame(total,index=["Monday","Tuesday","Wednesday","Thursday","Friday"],columns=["Total"])
df

Total
Monday        88
Tuesday      314
Wednesday    438
Thursday     426
Friday       402

In [24]:
weeklysales=pd.DataFrame(no_items_each_day,index=["Monday","Tuesday","Wednesday","Thursday","Friday"],columns=["Almond butter","Peanut Butter","Cashew butter"])
weeklysales

Almond butter  Peanut Butter  Cashew butter
Monday                 2              7              1
Tuesday                9              4             16
Wednesday             11             14             18
Thursday              13             13             16
Friday                15             18              9

In [25]:
weeklysales["Total($)"]=total

In [26]:
weeklysales

Almond butter  Peanut Butter  Cashew butter  Total($)
Monday                 2              7              1        88
Tuesday                9              4             16       314
Wednesday             11             14             18       438
Thursday              13             13             16       426
Friday                15             18              9       402

## Sorting Arrays

In [29]:
random1=np.random.randint(1,10,size=(3,5))
random1

array([[2, 6, 7, 9, 6],
       [8, 2, 2, 2, 1],
       [2, 9, 2, 2, 5]])

In [30]:
np.sort(random1)

array([[2, 6, 6, 7, 9],
       [1, 2, 2, 2, 8],
       [2, 2, 2, 5, 9]])

In [31]:
np.argsort(random1)

array([[0, 1, 4, 2, 3],
       [4, 1, 2, 3, 0],
       [0, 2, 3, 4, 1]], dtype=int64)

In [32]:
np.argmin(random1)

9

## Practical Example- Numpy in Action!!!

![](./numpy-images/car-photo.png)

In [1]:
from matplotlib.image import imread

In [6]:
car=imread("./numpy-images/car-photo.png")

In [7]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [8]:
car.size

991300

In [9]:
car.shape

(431, 575, 4)